# Generated by Django 5.2.8 on 2026-01-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seraphic', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
    ]
